disabled_rules:
  - line_length
  - trailing_comma
  - syntactic_sugar
  - todo
  - nesting
  - variable_name
  - empty_parentheses_with_trailing_closure
  - control_statement
  - force_try
  - function_parameter_count
  - closure_parameter_position
  - force_cast
  - type_name

included:
  - Sources
  - Tests
