disabled_rules:
  - line_length
  - trailing_comma
  - syntactic_sugar
  - todo
  - nesting
  - variable_name
  - force_try
  - function_parameter_count
  - force_cast
  - type_name

included:
  - Sources
  - Tests
