disabled_rules:
  - todo
  - variable_name
  - force_try
  - force_cast

included:
  - Sources
  - Tests

excluded:
  - Carthage/Checkouts
  - Tests/NimbleTests/XCTestManifests.swift
  - Tests/NimbleTests/Helpers/XCTestCaseProvider.swift

trailing_comma:
  mandatory_comma: true

line_length:
  ignores_comments: true
  ignores_function_declarations: true
