osx_image: xcode7
language: objective-c

install:
  - git submodule update --init --recursive

env:
  matrix:
    - NIMBLE_RUNTIME_IOS_SDK_VERSION=9.0 TYPE=ios
    - NIMBLE_RUNTIME_OSX_SDK_VERSION=10.10 TYPE=osx

script: ./test $TYPE
